set_property SRC_FILE_INFO {cfile:/home/chiwei/work/checkout/kcu116/kcu116_ibert/work/ibert_bank_all/ibert_bank_all_ex/ibert_bank_all_ex.srcs/sources_1/ip/ibert_bank_all/synth/ibert_bank_all.xdc rfile:../../../ibert_bank_all_ex.srcs/sources_1/ip/ibert_bank_all/synth/ibert_bank_all.xdc id:1 order:EARLY} [current_design]
set_property SRC_FILE_INFO {cfile:/home/chiwei/work/checkout/kcu116/kcu116_ibert/work/ibert_bank_all/ibert_bank_all_ex/ibert_bank_all_ex.srcs/sources_1/ip/ibert_bank_all/synth/attributes.xdc rfile:../../../ibert_bank_all_ex.srcs/sources_1/ip/ibert_bank_all/synth/attributes.xdc id:2 order:EARLY} [current_design]
set_property src_info {type:XDC file:1 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTYE4_CHANNEL_X0Y0 [get_cells inst/QUAD[0].u_q/CH[0].u_ch/u_gtye4_channel]
set_property src_info {type:XDC file:1 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTYE4_CHANNEL_X0Y1 [get_cells inst/QUAD[0].u_q/CH[1].u_ch/u_gtye4_channel]
set_property src_info {type:XDC file:1 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTYE4_CHANNEL_X0Y2 [get_cells inst/QUAD[0].u_q/CH[2].u_ch/u_gtye4_channel]
set_property src_info {type:XDC file:1 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTYE4_CHANNEL_X0Y3 [get_cells inst/QUAD[0].u_q/CH[3].u_ch/u_gtye4_channel]
set_property src_info {type:XDC file:1 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTYE4_COMMON_X0Y0 [get_cells inst/QUAD[0].u_q/u_common/u_gtye4_common]
set_property src_info {type:XDC file:1 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTYE4_CHANNEL_X0Y4 [get_cells inst/QUAD[1].u_q/CH[0].u_ch/u_gtye4_channel]
set_property src_info {type:XDC file:1 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTYE4_CHANNEL_X0Y5 [get_cells inst/QUAD[1].u_q/CH[1].u_ch/u_gtye4_channel]
set_property src_info {type:XDC file:1 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTYE4_CHANNEL_X0Y6 [get_cells inst/QUAD[1].u_q/CH[2].u_ch/u_gtye4_channel]
set_property src_info {type:XDC file:1 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTYE4_CHANNEL_X0Y7 [get_cells inst/QUAD[1].u_q/CH[3].u_ch/u_gtye4_channel]
set_property src_info {type:XDC file:1 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTYE4_COMMON_X0Y1 [get_cells inst/QUAD[1].u_q/u_common/u_gtye4_common]
set_property src_info {type:XDC file:1 line:82 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTYE4_CHANNEL_X0Y8 [get_cells inst/QUAD[2].u_q/CH[0].u_ch/u_gtye4_channel]
set_property src_info {type:XDC file:1 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTYE4_CHANNEL_X0Y9 [get_cells inst/QUAD[2].u_q/CH[1].u_ch/u_gtye4_channel]
set_property src_info {type:XDC file:1 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTYE4_CHANNEL_X0Y10 [get_cells inst/QUAD[2].u_q/CH[2].u_ch/u_gtye4_channel]
set_property src_info {type:XDC file:1 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTYE4_CHANNEL_X0Y11 [get_cells inst/QUAD[2].u_q/CH[3].u_ch/u_gtye4_channel]
set_property src_info {type:XDC file:1 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTYE4_COMMON_X0Y2 [get_cells inst/QUAD[2].u_q/u_common/u_gtye4_common]
set_property src_info {type:XDC file:1 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTYE4_CHANNEL_X0Y12 [get_cells inst/QUAD[3].u_q/CH[0].u_ch/u_gtye4_channel]
set_property src_info {type:XDC file:1 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTYE4_CHANNEL_X0Y13 [get_cells inst/QUAD[3].u_q/CH[1].u_ch/u_gtye4_channel]
set_property src_info {type:XDC file:1 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTYE4_CHANNEL_X0Y14 [get_cells inst/QUAD[3].u_q/CH[2].u_ch/u_gtye4_channel]
set_property src_info {type:XDC file:1 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTYE4_CHANNEL_X0Y15 [get_cells inst/QUAD[3].u_q/CH[3].u_ch/u_gtye4_channel]
set_property src_info {type:XDC file:1 line:91 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTYE4_COMMON_X0Y3 [get_cells inst/QUAD[3].u_q/u_common/u_gtye4_common]
set_property src_info {type:XDC file:1 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {inst/QUAD[*].u_q/CH[*].u_ch/u_gtye4_channel/TXRATE[*]}]
set_property src_info {type:XDC file:1 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {inst/QUAD[*].u_q/CH[*].u_ch/u_gtye4_channel/RXRATE[*]}]
set_property src_info {type:XDC file:1 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins {inst/QUAD[0].u_q/u_common/u_gtye4_common/QPLL0REFCLKSEL[0]}]
set_property src_info {type:XDC file:1 line:99 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {inst/QUAD[0].u_q/u_common/u_gtye4_common/QPLL0REFCLKSEL[1]}]
set_property src_info {type:XDC file:1 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins {inst/QUAD[0].u_q/u_common/u_gtye4_common/QPLL0REFCLKSEL[2]}]
set_property src_info {type:XDC file:1 line:102 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {inst/QUAD[0].u_q/u_common/u_gtye4_common/QPLL1REFCLKSEL[0]}]
set_property src_info {type:XDC file:1 line:103 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {inst/QUAD[0].u_q/u_common/u_gtye4_common/QPLL1REFCLKSEL[1]}]
set_property src_info {type:XDC file:1 line:104 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {inst/QUAD[0].u_q/u_common/u_gtye4_common/QPLL1REFCLKSEL[2]}]
set_property src_info {type:XDC file:1 line:106 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins {inst/QUAD[0].u_q/CH[*].u_ch/u_gtye4_channel/CPLLREFCLKSEL[0]}]
set_property src_info {type:XDC file:1 line:107 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {inst/QUAD[0].u_q/CH[*].u_ch/u_gtye4_channel/CPLLREFCLKSEL[1]}]
set_property src_info {type:XDC file:1 line:108 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {inst/QUAD[0].u_q/CH[*].u_ch/u_gtye4_channel/CPLLREFCLKSEL[2]}]
set_property src_info {type:XDC file:1 line:111 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins {inst/QUAD[0].u_q/CH[*].u_ch/u_gtye4_channel/TXPLLCLKSEL[0]}]
set_property src_info {type:XDC file:1 line:112 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins {inst/QUAD[0].u_q/CH[*].u_ch/u_gtye4_channel/TXPLLCLKSEL[1]}]
set_property src_info {type:XDC file:1 line:115 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins {inst/QUAD[0].u_q/CH[*].u_ch/u_gtye4_channel/RXPLLCLKSEL[0]}]
set_property src_info {type:XDC file:1 line:116 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins {inst/QUAD[0].u_q/CH[*].u_ch/u_gtye4_channel/RXPLLCLKSEL[1]}]
set_property src_info {type:XDC file:1 line:120 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins {inst/QUAD[1].u_q/u_common/u_gtye4_common/QPLL0REFCLKSEL[0]}]
set_property src_info {type:XDC file:1 line:121 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {inst/QUAD[1].u_q/u_common/u_gtye4_common/QPLL0REFCLKSEL[1]}]
set_property src_info {type:XDC file:1 line:122 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {inst/QUAD[1].u_q/u_common/u_gtye4_common/QPLL0REFCLKSEL[2]}]
set_property src_info {type:XDC file:1 line:124 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {inst/QUAD[1].u_q/u_common/u_gtye4_common/QPLL1REFCLKSEL[0]}]
set_property src_info {type:XDC file:1 line:125 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {inst/QUAD[1].u_q/u_common/u_gtye4_common/QPLL1REFCLKSEL[1]}]
set_property src_info {type:XDC file:1 line:126 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {inst/QUAD[1].u_q/u_common/u_gtye4_common/QPLL1REFCLKSEL[2]}]
set_property src_info {type:XDC file:1 line:128 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins {inst/QUAD[1].u_q/CH[*].u_ch/u_gtye4_channel/CPLLREFCLKSEL[0]}]
set_property src_info {type:XDC file:1 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {inst/QUAD[1].u_q/CH[*].u_ch/u_gtye4_channel/CPLLREFCLKSEL[1]}]
set_property src_info {type:XDC file:1 line:130 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {inst/QUAD[1].u_q/CH[*].u_ch/u_gtye4_channel/CPLLREFCLKSEL[2]}]
set_property src_info {type:XDC file:1 line:133 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins {inst/QUAD[1].u_q/CH[*].u_ch/u_gtye4_channel/TXPLLCLKSEL[0]}]
set_property src_info {type:XDC file:1 line:134 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins {inst/QUAD[1].u_q/CH[*].u_ch/u_gtye4_channel/TXPLLCLKSEL[1]}]
set_property src_info {type:XDC file:1 line:137 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins {inst/QUAD[1].u_q/CH[*].u_ch/u_gtye4_channel/RXPLLCLKSEL[0]}]
set_property src_info {type:XDC file:1 line:138 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins {inst/QUAD[1].u_q/CH[*].u_ch/u_gtye4_channel/RXPLLCLKSEL[1]}]
set_property src_info {type:XDC file:1 line:142 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {inst/QUAD[2].u_q/u_common/u_gtye4_common/QPLL0REFCLKSEL[0]}]
set_property src_info {type:XDC file:1 line:143 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins {inst/QUAD[2].u_q/u_common/u_gtye4_common/QPLL0REFCLKSEL[1]}]
set_property src_info {type:XDC file:1 line:144 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {inst/QUAD[2].u_q/u_common/u_gtye4_common/QPLL0REFCLKSEL[2]}]
set_property src_info {type:XDC file:1 line:146 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {inst/QUAD[2].u_q/u_common/u_gtye4_common/QPLL1REFCLKSEL[0]}]
set_property src_info {type:XDC file:1 line:147 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {inst/QUAD[2].u_q/u_common/u_gtye4_common/QPLL1REFCLKSEL[1]}]
set_property src_info {type:XDC file:1 line:148 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {inst/QUAD[2].u_q/u_common/u_gtye4_common/QPLL1REFCLKSEL[2]}]
set_property src_info {type:XDC file:1 line:150 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins {inst/QUAD[2].u_q/CH[*].u_ch/u_gtye4_channel/CPLLREFCLKSEL[0]}]
set_property src_info {type:XDC file:1 line:151 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {inst/QUAD[2].u_q/CH[*].u_ch/u_gtye4_channel/CPLLREFCLKSEL[1]}]
set_property src_info {type:XDC file:1 line:152 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {inst/QUAD[2].u_q/CH[*].u_ch/u_gtye4_channel/CPLLREFCLKSEL[2]}]
set_property src_info {type:XDC file:1 line:155 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins {inst/QUAD[2].u_q/CH[*].u_ch/u_gtye4_channel/TXPLLCLKSEL[0]}]
set_property src_info {type:XDC file:1 line:156 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins {inst/QUAD[2].u_q/CH[*].u_ch/u_gtye4_channel/TXPLLCLKSEL[1]}]
set_property src_info {type:XDC file:1 line:159 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins {inst/QUAD[2].u_q/CH[*].u_ch/u_gtye4_channel/RXPLLCLKSEL[0]}]
set_property src_info {type:XDC file:1 line:160 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins {inst/QUAD[2].u_q/CH[*].u_ch/u_gtye4_channel/RXPLLCLKSEL[1]}]
set_property src_info {type:XDC file:1 line:164 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {inst/QUAD[3].u_q/u_common/u_gtye4_common/QPLL0REFCLKSEL[0]}]
set_property src_info {type:XDC file:1 line:165 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {inst/QUAD[3].u_q/u_common/u_gtye4_common/QPLL0REFCLKSEL[1]}]
set_property src_info {type:XDC file:1 line:166 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins {inst/QUAD[3].u_q/u_common/u_gtye4_common/QPLL0REFCLKSEL[2]}]
set_property src_info {type:XDC file:1 line:168 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {inst/QUAD[3].u_q/u_common/u_gtye4_common/QPLL1REFCLKSEL[0]}]
set_property src_info {type:XDC file:1 line:169 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {inst/QUAD[3].u_q/u_common/u_gtye4_common/QPLL1REFCLKSEL[1]}]
set_property src_info {type:XDC file:1 line:170 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {inst/QUAD[3].u_q/u_common/u_gtye4_common/QPLL1REFCLKSEL[2]}]
set_property src_info {type:XDC file:1 line:172 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins {inst/QUAD[3].u_q/CH[*].u_ch/u_gtye4_channel/CPLLREFCLKSEL[0]}]
set_property src_info {type:XDC file:1 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {inst/QUAD[3].u_q/CH[*].u_ch/u_gtye4_channel/CPLLREFCLKSEL[1]}]
set_property src_info {type:XDC file:1 line:174 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {inst/QUAD[3].u_q/CH[*].u_ch/u_gtye4_channel/CPLLREFCLKSEL[2]}]
set_property src_info {type:XDC file:1 line:177 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins {inst/QUAD[3].u_q/CH[*].u_ch/u_gtye4_channel/TXPLLCLKSEL[0]}]
set_property src_info {type:XDC file:1 line:178 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins {inst/QUAD[3].u_q/CH[*].u_ch/u_gtye4_channel/TXPLLCLKSEL[1]}]
set_property src_info {type:XDC file:1 line:181 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins {inst/QUAD[3].u_q/CH[*].u_ch/u_gtye4_channel/RXPLLCLKSEL[0]}]
set_property src_info {type:XDC file:1 line:182 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins {inst/QUAD[3].u_q/CH[*].u_ch/u_gtye4_channel/RXPLLCLKSEL[1]}]
set_property src_info {type:XDC file:1 line:184 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {inst/QUAD[*].u_q/CH[*].u_ch/u_gtye4_channel/TXOUTCLKSEL[2]}]
set_property src_info {type:XDC file:1 line:185 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins {inst/QUAD[*].u_q/CH[*].u_ch/u_gtye4_channel/TXOUTCLKSEL[1]}]
set_property src_info {type:XDC file:1 line:186 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {inst/QUAD[*].u_q/CH[*].u_ch/u_gtye4_channel/TXOUTCLKSEL[0]}]
set_property src_info {type:XDC file:1 line:188 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {inst/QUAD[*].u_q/CH[*].u_ch/u_gtye4_channel/RXOUTCLKSEL[2]}]
set_property src_info {type:XDC file:1 line:189 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins {inst/QUAD[*].u_q/CH[*].u_ch/u_gtye4_channel/RXOUTCLKSEL[1]}]
set_property src_info {type:XDC file:1 line:190 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {inst/QUAD[*].u_q/CH[*].u_ch/u_gtye4_channel/RXOUTCLKSEL[0]}]
set_property src_info {type:XDC file:2 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {inst/QUAD[0].u_q/u_common/u_gtye4_common/QPLLRSVD2[0]}]
set_property src_info {type:XDC file:2 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {inst/QUAD[0].u_q/u_common/u_gtye4_common/QPLLRSVD2[1]}]
set_property src_info {type:XDC file:2 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {inst/QUAD[0].u_q/u_common/u_gtye4_common/QPLLRSVD2[2]}]
set_property src_info {type:XDC file:2 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {inst/QUAD[0].u_q/u_common/u_gtye4_common/QPLLRSVD2[3]}]
set_property src_info {type:XDC file:2 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {inst/QUAD[0].u_q/u_common/u_gtye4_common/QPLLRSVD2[4]}]
set_property src_info {type:XDC file:2 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {inst/QUAD[0].u_q/u_common/u_gtye4_common/QPLLRSVD3[0]}]
set_property src_info {type:XDC file:2 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {inst/QUAD[0].u_q/u_common/u_gtye4_common/QPLLRSVD3[1]}]
set_property src_info {type:XDC file:2 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {inst/QUAD[0].u_q/u_common/u_gtye4_common/QPLLRSVD3[2]}]
set_property src_info {type:XDC file:2 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {inst/QUAD[0].u_q/u_common/u_gtye4_common/QPLLRSVD3[3]}]
set_property src_info {type:XDC file:2 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {inst/QUAD[0].u_q/u_common/u_gtye4_common/QPLLRSVD3[4]}]
set_property src_info {type:XDC file:2 line:586 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {inst/QUAD[1].u_q/u_common/u_gtye4_common/QPLLRSVD2[0]}]
set_property src_info {type:XDC file:2 line:587 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {inst/QUAD[1].u_q/u_common/u_gtye4_common/QPLLRSVD2[1]}]
set_property src_info {type:XDC file:2 line:588 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {inst/QUAD[1].u_q/u_common/u_gtye4_common/QPLLRSVD2[2]}]
set_property src_info {type:XDC file:2 line:589 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {inst/QUAD[1].u_q/u_common/u_gtye4_common/QPLLRSVD2[3]}]
set_property src_info {type:XDC file:2 line:590 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {inst/QUAD[1].u_q/u_common/u_gtye4_common/QPLLRSVD2[4]}]
set_property src_info {type:XDC file:2 line:591 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {inst/QUAD[1].u_q/u_common/u_gtye4_common/QPLLRSVD3[0]}]
set_property src_info {type:XDC file:2 line:592 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {inst/QUAD[1].u_q/u_common/u_gtye4_common/QPLLRSVD3[1]}]
set_property src_info {type:XDC file:2 line:593 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {inst/QUAD[1].u_q/u_common/u_gtye4_common/QPLLRSVD3[2]}]
set_property src_info {type:XDC file:2 line:594 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {inst/QUAD[1].u_q/u_common/u_gtye4_common/QPLLRSVD3[3]}]
set_property src_info {type:XDC file:2 line:595 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {inst/QUAD[1].u_q/u_common/u_gtye4_common/QPLLRSVD3[4]}]
set_property src_info {type:XDC file:2 line:1170 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {inst/QUAD[2].u_q/u_common/u_gtye4_common/QPLLRSVD2[0]}]
set_property src_info {type:XDC file:2 line:1171 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {inst/QUAD[2].u_q/u_common/u_gtye4_common/QPLLRSVD2[1]}]
set_property src_info {type:XDC file:2 line:1172 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {inst/QUAD[2].u_q/u_common/u_gtye4_common/QPLLRSVD2[2]}]
set_property src_info {type:XDC file:2 line:1173 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {inst/QUAD[2].u_q/u_common/u_gtye4_common/QPLLRSVD2[3]}]
set_property src_info {type:XDC file:2 line:1174 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {inst/QUAD[2].u_q/u_common/u_gtye4_common/QPLLRSVD2[4]}]
set_property src_info {type:XDC file:2 line:1175 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {inst/QUAD[2].u_q/u_common/u_gtye4_common/QPLLRSVD3[0]}]
set_property src_info {type:XDC file:2 line:1176 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {inst/QUAD[2].u_q/u_common/u_gtye4_common/QPLLRSVD3[1]}]
set_property src_info {type:XDC file:2 line:1177 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {inst/QUAD[2].u_q/u_common/u_gtye4_common/QPLLRSVD3[2]}]
set_property src_info {type:XDC file:2 line:1178 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {inst/QUAD[2].u_q/u_common/u_gtye4_common/QPLLRSVD3[3]}]
set_property src_info {type:XDC file:2 line:1179 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {inst/QUAD[2].u_q/u_common/u_gtye4_common/QPLLRSVD3[4]}]
set_property src_info {type:XDC file:2 line:1754 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {inst/QUAD[3].u_q/u_common/u_gtye4_common/QPLLRSVD2[0]}]
set_property src_info {type:XDC file:2 line:1755 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {inst/QUAD[3].u_q/u_common/u_gtye4_common/QPLLRSVD2[1]}]
set_property src_info {type:XDC file:2 line:1756 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {inst/QUAD[3].u_q/u_common/u_gtye4_common/QPLLRSVD2[2]}]
set_property src_info {type:XDC file:2 line:1757 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {inst/QUAD[3].u_q/u_common/u_gtye4_common/QPLLRSVD2[3]}]
set_property src_info {type:XDC file:2 line:1758 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {inst/QUAD[3].u_q/u_common/u_gtye4_common/QPLLRSVD2[4]}]
set_property src_info {type:XDC file:2 line:1759 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {inst/QUAD[3].u_q/u_common/u_gtye4_common/QPLLRSVD3[0]}]
set_property src_info {type:XDC file:2 line:1760 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {inst/QUAD[3].u_q/u_common/u_gtye4_common/QPLLRSVD3[1]}]
set_property src_info {type:XDC file:2 line:1761 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {inst/QUAD[3].u_q/u_common/u_gtye4_common/QPLLRSVD3[2]}]
set_property src_info {type:XDC file:2 line:1762 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {inst/QUAD[3].u_q/u_common/u_gtye4_common/QPLLRSVD3[3]}]
set_property src_info {type:XDC file:2 line:1763 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {inst/QUAD[3].u_q/u_common/u_gtye4_common/QPLLRSVD3[4]}]
