
# file: ibert_bank_all.xdc
####################################################################################
##   ____  ____ 
##  /   /\/   /
## /___/  \  /    Vendor: Xilinx
## \   \   \/     Version : 2012.3
##  \   \         Application : IBERT Ultrascale
##  /   /         Filename : example_ibert_bank_all.xdc
## /___/   /\     
## \   \  /  \ 
##  \___\/\___\
##
##
## 
## Generated by Xilinx IBERT Ultrascale
##**************************************************************************
##
## Icon Constraints
##
create_clock -name D_CLK -period 3.333 [get_ports gty_sysclkp_i]
set_clock_groups -group [get_clocks D_CLK -include_generated_clocks] -asynchronous

set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER true [get_debug_cores dbg_hub]
##
##gtrefclk lock constraints
##
set_property PACKAGE_PIN V7 [get_ports gty_refclk0p_i[0]]
set_property PACKAGE_PIN V6 [get_ports gty_refclk0n_i[0]]
set_property PACKAGE_PIN T7 [get_ports gty_refclk1p_i[0]]
set_property PACKAGE_PIN T6 [get_ports gty_refclk1n_i[0]]
set_property PACKAGE_PIN P7 [get_ports gty_refclk0p_i[1]]
set_property PACKAGE_PIN P6 [get_ports gty_refclk0n_i[1]]
set_property PACKAGE_PIN M7 [get_ports gty_refclk1p_i[1]]
set_property PACKAGE_PIN M6 [get_ports gty_refclk1n_i[1]]
set_property PACKAGE_PIN K7 [get_ports gty_refclk0p_i[2]]
set_property PACKAGE_PIN K6 [get_ports gty_refclk0n_i[2]]
set_property PACKAGE_PIN H7 [get_ports gty_refclk1p_i[2]]
set_property PACKAGE_PIN H6 [get_ports gty_refclk1n_i[2]]
##
## Refclk constraints
##
create_clock -name gtrefclk0_1 -period 10.0 [get_ports gty_refclk0p_i[0]]
create_clock -name gtrefclk1_1 -period 10.0 [get_ports gty_refclk1p_i[0]]
set_clock_groups -group [get_clocks gtrefclk0_1 -include_generated_clocks] -asynchronous
set_clock_groups -group [get_clocks gtrefclk1_1 -include_generated_clocks] -asynchronous
create_clock -name gtrefclk0_2 -period 6.4 [get_ports gty_refclk0p_i[1]]
create_clock -name gtrefclk1_2 -period 6.4 [get_ports gty_refclk1p_i[1]]
set_clock_groups -group [get_clocks gtrefclk0_2 -include_generated_clocks] -asynchronous
set_clock_groups -group [get_clocks gtrefclk1_2 -include_generated_clocks] -asynchronous
create_clock -name gtrefclk0_3 -period 6.4 [get_ports gty_refclk0p_i[2]]
create_clock -name gtrefclk1_3 -period 6.4 [get_ports gty_refclk1p_i[2]]
set_clock_groups -group [get_clocks gtrefclk0_3 -include_generated_clocks] -asynchronous
set_clock_groups -group [get_clocks gtrefclk1_3 -include_generated_clocks] -asynchronous
##
## System clock pin locs and timing constraints
##
set_property PACKAGE_PIN K22 [get_ports gty_sysclkp_i]
set_property IOSTANDARD DIFF_SSTL12 [get_ports gty_sysclkp_i]
